.TH PORTLIB 3 "1999-May-21" "ntcc"
.SH NAME 
PortLib
.SH SYNOPSIS
f77 ... -L<target>/lib -lportlib
.sp
f90 ... -L<target>/lib -lportlib
.sp
[ at PPPL <target> = $NTCCHOME ]
.SH DESCRIPTION
A library of interfaces to operating system functions
(such as "getenv", "getcwd", "system", etc), which hides
operating system dependency from the user code.

.SH "SEE ALSO"

.B http:/w3.pppl.gov/NTCC/Portlib/portlib.html


